name: Azure Prod Deployment

on:
  workflow_dispatch: 

jobs:
  build_and_deploy_swa_job:
    runs-on: ubuntu-latest
    name: Publish and Deploy Static Web App Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish Web Project
        working-directory: ./Web
        run: |
          dotnet publish --configuration Release --output bin
      - name: Remove Blazor Environment Header
        uses: tnikFi/json-file-transform@v2
        with:
          files: '**/staticwebapp.config.json'
          key-value-pairs: |
            globalHeaders.blazor-environment=
      - name: Deploy Web Project
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_STAGING_PROD_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "Web/bin/wwwroot" # App source code path
          production_branch: "main"
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  build_and_deploy_api_job:
    runs-on: ubuntu-latest
    name: Publish and Deploy Web App Job (Api)
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish API Project
        working-directory: ./Api
        run: |
          dotnet publish --configuration Release --output bin/publish
      - name: Deploy Api Project
        uses: azure/webapps-deploy@v3
        with:
          app-name: "bodylinesports-prod-api"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROD_PROFILE }}
          package: 'Api/bin/publish' 
  build_and_deploy_admin_job:
    runs-on: ubuntu-latest
    name: Publish and Deploy Web App Job (Admin)
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish Admin Project
        working-directory: ./Admin
        run: |
          dotnet publish --configuration Release --output bin/publish
      - name: Deploy Api Project
        uses: azure/webapps-deploy@v3
        with:
          app-name: "bodylinesports-prod-admin"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROD_ADMIN_PROFILE }}
          package: 'Admin/bin/publish'