name: Azure Prod Deployment

on:
  workflow_dispatch: 

jobs:
  build_and_deploy_swa_job:
    runs-on: ubuntu-latest
    name: Publish and Deploy Static Web App Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Publish Web Project
        working-directory: ./Web
        run: |
          dotnet publish --configuration Release --output bin
      - name: Replace values in JSON file
        uses: tnikFi/json-file-transform@v1
        with:
          files: '**/staticwebapp.config.json'
          key-value-pairs: |
            globalHeaders.blazor-environment=
      - name: Deploy Web Project
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_STAGING_PROD_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "Web/bin/wwwroot" # App source code path
          deployment_environment: "staging"
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  build_and_deploy_webapp_job:
    runs-on: ubuntu-latest
    name: Publish and Deploy Web App Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Publish API Project
        working-directory: ./Api
        run: |
          dotnet publish --configuration Release --output bin/publish
      - name: Deploy Api Project
        uses: azure/webapps-deploy@v2
        with:
          app-name: "bodylinesports-staging-api"
          publish-profile: ${{ secrets.AZURE_PUBLISH_STAGING_PROFILE }}
          package: 'Api/bin/publish' 